version: "3.8"
services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      REDISHOST: redis
      REDISPORT: 6379
      REDISPASSWORD: ""
      REDIS_DB: 0
      CAPSOLVER_API_KEY: ${CAPSOLVER_API_KEY}
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      REDISHOST: redis
      REDISPORT: 6379
      REDISPASSWORD: ""
      REDIS_DB: 0
      CAPSOLVER_API_KEY: ${CAPSOLVER_API_KEY}
    depends_on:
      - redis
    # Uncomment the following line to scale workers (e.g., 3 instances)
    # deploy:
    #   replicas: 3

volumes:
  redis_data:
